image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
    rm -rf build
    mkdir build
    cd build
    
    cmake c:\projects\source
    
    cmake --build . --config "Debug"
